import sqlite3
conn = sqlite3.connect(\"app.db\")
cursor = conn.cursor()
cursor.execute(\"SELECT * FROM users\")
print(\"用户信息表结构:\")
print([description[0] for description in cursor.description])
rows = cursor.fetchall()
print(\"用户数据:\")
for row in rows: print(row)
conn.close()
